<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Cart $block */

/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
/** @var \Magento\Wishlist\ViewModel\AllowedQuantity $viewModel */
$viewModel = $block->getData('allowedQuantityViewModel');
$allowedQty = $viewModel->setItem($item)->getMinMaxQty();

$productInquiryHelper = $this->helper(\Sparsh\ProductInquiry\Helper\Data::class);
$allowAddToCart = $productInquiryHelper->getAllowAddtocart($product->getId());
$productInquirySku = $product->getSku();
$productInquiryName = $product->getName();

$inquiryTitle = $productInquiryHelper->getInquiryTitle($product->getId());
?>
<?php foreach ($block->getChildNames() as $childName): ?>
    <?= /* @noEscape */ $block->getLayout()->renderElement($childName, false) ?>
<?php endforeach;?>
<div class="box-tocart">
    <fieldset class="fieldset">
        <?php if ($item->canHaveQty() && $product->isVisibleInSiteVisibility()): ?>
            <div class="field qty">
                <label class="label" for="qty[<?= $escaper->escapeHtmlAttr($item->getId()) ?>]"><span><?= $escaper->escapeHtml(__('Qty')) ?></span></label>
                <div class="control">
                    <input type="number" data-role="qty" id="qty[<?= $escaper->escapeHtmlAttr($item->getId()) ?>]" class="input-text qty" data-validate="{'required-number':true,'validate-greater-than-zero':true, 'validate-item-quantity':{'minAllowed':<?= /* @noEscape */ $allowedQty['minAllowed'] ?>,'maxAllowed':<?= /* @noEscape */ $allowedQty['maxAllowed'] ?>}}"
                           name="qty[<?= $escaper->escapeHtmlAttr($item->getId()) ?>]" value="<?= /* @noEscape */ (int)($block->getAddToCartQty($item) * 1) ?>" <?= $product->isSaleable() ? '' : 'disabled="disabled"' ?>>
                </div>
            </div>
        <?php endif; ?>
        <?php if ($product->isSaleable() && $allowAddToCart): ?>
            <div class="product-item-actions">
                <div class="actions-primary">
                    <button type="button" data-role="tocart" data-post='<?= /* @noEscape */ $block->getItemAddToCartParams($item) ?>' title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>" data-item-id="<?= $escaper->escapeHtmlAttr($item->getId()) ?>" class="action tocart primary">
                        <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                    </button>
                </div>
            </div>
        <?php elseif(!$product->isSaleable()): ?>
            <?php if ($product->getIsSalable()): ?>
                <p class="available stock" title="<?= $escaper->escapeHtmlAttr(__('Availability')) ?>">
                    <span><?= $escaper->escapeHtml(__('In stock')) ?></span>
                </p>
            <?php else: ?>
                <p class="unavailable stock" title="<?= $escaper->escapeHtmlAttr(__('Availability')) ?>">
                    <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span>
                </p>
            <?php endif; ?>
        <?php endif; ?>
    </fieldset>
</div>
<?php if($inquiryTitle) { ?>
    <button
            type="button"
            title="<?php echo $inquiryTitle; ?>"
            class="action tocart primary sparsh_product_inquiry_link"
            data-product-inquiry-sku="<?php echo $escaper->escapeHtmlAttr($productInquirySku);?>"
            data-product-inquiry-name="<?php echo $escaper->escapeHtmlAttr($productInquiryName);?>" >
        <span><?php echo $inquiryTitle; ?></span>
    </button>
<?php } ?>