<form id="edit_form" action="<?= $block->getUrl('test_form/index/save')?>" method="post" enctype="multipart/form-data">
    <?= $block->getBlockHtml('formkey') ?>
    <div class="admin__field">
            <div class="admin__field-control">
                <input type="hidden" id="username" name="entity_id" class="input-text"/>
            </div>
        </div>
        <div class="admin__field">
            <label class="admin__field-label" for="username"><span><?= $block->escapeHtml(__('Username')) ?></span></label>
            <div class="admin__field-control">
                <input type="text" id="username" name="username" class="input-text"/>
            </div>
        </div>
        <div class="admin__field">
            <label class="admin__field-label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="admin__field-control">
                <input type="text" id="email" name="email" class="input-text"/>
            </div>
        </div>
        <div class="admin__field">
            <label class="admin__field-label" for="telephone"><span><?= $block->escapeHtml(__('Telephone')) ?></span></label>
            <div class="admin__field-control">
                <input type="text" id="telephone" name="telephone" class="input-text"/>
            </div>
        </div>
        <div class="admin__actions-toolbar">
            <div class="admin__actions-primary">
                <button type="submit" class="action-default scalable save primary">
                    <span><?= $block->escapeHtml(__('Save')) ?></span>
                </button>
            </div>
        </div>
    </div>
</form>